// Generated by IcedCoffeeScript 1.4.0c
(function() {

  $(document).ready(function() {
    return CodeMirror.fromTextArea(document.getElementById('code'), {
      mode: 'javascript'
    });
  });

}).call(this);
